use strata_identifiers::{OLBlockCommitment, OLBlockId};
use strata_primitives::epoch::EpochCommitment;
use thiserror::Error;

/// Return type for worker messages.
pub type WorkerResult<T> = Result<T, WorkerError>;

#[derive(Debug, Error)]
pub enum WorkerError {
    #[error("missing OL block {0}")]
    MissingBlock(OLBlockId),

    /// This usually means that we didn't execute the previous block.
    #[error("missing pre-state to execute block {0:?}")]
    MissingPreState(OLBlockCommitment),

    /// This might point to a database corruption or misused admin commands.
    /// The worker should not have tried to access block outputs that are
    /// missing.
    #[error("missing exec output for block {0:?}")]
    MissingBlockOutput(OLBlockCommitment),

    /// Missing write batch for a specific block, used for post-state reconstruction
    #[error("missing write batch for block {0:?}")]
    MissingWriteBatch(OLBlockCommitment),

    /// Missing OL state for a block
    #[error("missing OL state for block {0:?}")]
    MissingOLState(OLBlockCommitment),

    /// This means that we haven't executed the block that's the terminal for an epoch.
    #[error("missing inner post-state of epoch {0} terminal {1:?}")]
    MissingEpochInnerPostState(u64, OLBlockCommitment),

    /// Invalid execution payload for a block.
    #[error("invalid execution payload for block {0:?}")]
    InvalidExecPayload(OLBlockCommitment),

    /// Missing epoch summary for a given epoch commitment.
    #[error("missing summary for epoch commitment {0:?}")]
    MissingEpochSummary(EpochCommitment),

    /// Generated by the worker handle when the worker has exited before being
    /// able to process a message we were trying to send.
    #[error("chain worker exited")]
    WorkerExited,

    /// Block execution error.
    #[error("block execution: {0}")]
    Exec(String),

    /// EE block execution error.
    #[error("EE block execution: {0}")]
    ExecEnvEngine(#[from] strata_eectl::errors::EngineError),

    /// Missing required dependency.
    #[error("missing required dependency: {0}")]
    MissingDependency(&'static str),

    /// Shutdown before genesis.
    #[error("shutdown before genesis")]
    ShutdownBeforeGenesis,

    /// Missing genesis block.
    #[error("genesis block not found at slot 0")]
    MissingGenesisBlock,

    /// Worker not initialized.
    #[error("worker not initialized")]
    NotInitialized,

    /// Unexpected error.
    #[error("unexpected error: {0}")]
    Unexpected(String),

    /// Not yet implemented.
    #[error("not yet implemented")]
    Unimplemented,

    /// Database error.
    #[error("database error: {0}")]
    Database(String),
}
