//! Generic cache utility for database operations with error-type flexibility.
//!
//! This module provides a generic LRU cache implementation that works with any error type,
//! enabling different crates to use their own error types while maintaining the same caching
//! infrastructure.
//!
//! The cache is designed to work seamlessly with the operations generated by `inst_ops_generic!`
//! and handles concurrent access, pending operations, and error states efficiently.

use std::error;
use std::future::Future;
use std::hash::Hash;
use std::num::NonZeroUsize;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;

use tokio::sync::{broadcast, Mutex, RwLock};
use tracing::*;

use crate::exec::OpsError;

/// Entry for something we can put into the cache without actually knowing what it is, and so we can
/// keep the reservation to it.
type CacheSlot<T, E> = Arc<RwLock<SlotState<T, E>>>;

/// Describes a cache entry that may be occupied, reserved for pending database read, or returned an
/// error from a database read.
///
/// The generic `E` parameter allows this to work with any error type that implements the
/// necessary traits.
#[derive(Debug)]
pub enum SlotState<T, E> {
    /// Authentic database entry that has been successfully fetched.
    Ready(T),

    /// A database fetch is happening in the background. Multiple tasks waiting for the same
    /// key will all receive the result via this broadcast channel.
    Pending(broadcast::Receiver<Result<T, E>>),

    /// An error happened fetching from the database. The error is cached to avoid repeated
    /// failed fetch attempts.
    Error(E),
}

/// Wrapper around a LRU cache that handles cache reservations and asynchronously waiting for
/// database operations in the background without keeping a global lock on the cache.
///
/// This cache is generic over the error type `E`, allowing it to be used with different error
/// types across different crates. The error type must implement `From<OpsError>` to handle
/// conversion of internal operation errors.
#[expect(
    missing_debug_implementations,
    reason = "Some inner types don't have Debug implementation"
)]
pub struct CacheTable<K, V, E> {
    cache: Mutex<lru::LruCache<K, CacheSlot<V, E>>>,
    len: AtomicUsize,
}

impl<K: Clone + Eq + Hash, V: Clone, E: From<OpsError> + error::Error + Clone> CacheTable<K, V, E> {
    /// Creates a new cache with some maximum capacity.
    ///
    /// This measures entries by *count* not their (serialized?) size, so ideally entries should
    /// consume similar amounts of memory to helps us best reason about real cache capacity.
    pub fn new(size: NonZeroUsize) -> Self {
        Self {
            cache: Mutex::new(lru::LruCache::new(size)),
            len: AtomicUsize::new(0),
        }
    }

    /// Gets the number of elements in the cache.
    #[allow(dead_code, clippy::allow_attributes, reason = "used for debugging")]
    pub async fn get_len_async(&self) -> usize {
        self.len.load(Ordering::Relaxed)
    }

    /// Gets the number of elements in the cache.
    #[allow(dead_code, clippy::allow_attributes, reason = "used for debugging")]
    pub fn get_len_blocking(&self) -> usize {
        self.len.load(Ordering::Relaxed)
    }

    /// Removes the entry for a particular cache entry.
    pub async fn purge_async(&self, k: &K) {
        let mut cache = self.cache.lock().await;
        cache.pop(k);
        self.len.store(cache.len(), Ordering::Relaxed);
    }

    /// Removes the entry for a particular cache entry.
    pub fn purge_blocking(&self, k: &K) {
        let mut cache = self.cache.blocking_lock();
        cache.pop(k);
        self.len.store(cache.len(), Ordering::Relaxed);
    }

    /// Removes all entries for which the predicate returns `true`.
    /// Returns the number of entries removed.
    ///
    /// This unfortunately has to clone as many keys from the cache as pass the
    /// predicate, which means it's capped at the maximum size of the cache, so
    /// that's not *so* bad.
    ///
    /// This might remove slots that are in the process of being filled.  Those
    /// operations will complete, but we won't retain those values.
    pub async fn purge_if_async(&self, mut pred: impl FnMut(&K) -> bool) -> usize {
        let mut cache = self.cache.lock().await;
        let keys_to_remove = cache
            .iter()
            .map(|(k, _v)| k)
            .filter(|k| pred(k)) // why can't I just pass pred?
            .cloned()
            .collect::<Vec<_>>();
        keys_to_remove.iter().for_each(|k| {
            cache.pop(k);
        });
        self.len.store(cache.len(), Ordering::Relaxed);
        keys_to_remove.len()
    }
    /// Removes all entries for which the predicate returns `true`.
    /// Returns the number of entries removed.
    ///
    /// This unfortunately has to clone as many keys from the cache as pass the
    /// predicate, which means it's capped at the maximum size of the cache, so
    /// that's not *so* bad.
    ///
    /// This might remove slots that are in the process of being filled.  Those
    /// operations will complete, but we won't retain those values.
    pub fn purge_if_blocking(&self, mut pred: impl FnMut(&K) -> bool) -> usize {
        let mut cache = self.cache.blocking_lock();
        let keys_to_remove = cache
            .iter()
            .map(|(k, _v)| k)
            .filter(|k| pred(k)) // why can't I just pass pred?
            .cloned()
            .collect::<Vec<_>>();
        keys_to_remove.iter().for_each(|k| {
            cache.pop(k);
        });
        self.len.store(cache.len(), Ordering::Relaxed);
        keys_to_remove.len()
    }

    /// Removes all entries from the cache.  Returns the number of entries
    /// removed.
    ///
    /// This might remove slots that are in the process of being filled.  Those
    /// operations will complete, but we won't retain those values.
    pub fn blocking_clear(&self) -> usize {
        let mut cache = self.cache.blocking_lock();
        let len = cache.len();
        cache.clear();
        self.len.store(0, Ordering::Relaxed);
        len
    }

    /// Removes all entries from the cache.  Returns the number of entries
    /// removed.
    ///
    /// This might remove slots that are in the process of being filled.  Those
    /// operations will complete, but we won't retain those values.
    pub async fn async_clear(&self) -> usize {
        let mut cache = self.cache.lock().await;
        let len = cache.len();
        cache.clear();
        self.len.store(0, Ordering::Relaxed);
        len
    }

    /// Inserts an entry into the table, dropping the previous value.
    pub async fn insert_async(&self, k: K, v: V) {
        let slot = Arc::new(RwLock::new(SlotState::Ready(v)));
        let mut cache = self.cache.lock().await;
        cache.put(k, slot);
        self.len.store(cache.len(), Ordering::Relaxed);
    }

    /// Inserts an entry into the table, dropping the previous value.
    pub fn insert_blocking(&self, k: K, v: V) {
        let slot = Arc::new(RwLock::new(SlotState::Ready(v)));
        let mut cache = self.cache.blocking_lock();
        cache.put(k, slot);
        self.len.store(cache.len(), Ordering::Relaxed);
    }

    /// Returns a clone of an entry from the cache, or invokes some function whose future loads the
    /// value from the underlying database.
    ///
    /// This is meant to be used with the `_fut` methods generated by the `gen_proxy` database
    /// proxies, e.g. `|| self.ops.get_block_data_fut(id).recv()`.
    pub async fn get_or_fetch<F>(&self, k: &K, fetch_fn: impl Fn() -> F) -> Result<V, E>
    where
        F: Future<Output = Result<V, E>>,
    {
        // See below comment about control flow.
        let (slot, complete_tx) = {
            let mut cache_guard = self.cache.lock().await;
            trace!("acquired cache lock");
            if let Some(entry_guard) = cache_guard.get(k).cloned() {
                drop(cache_guard);

                // Get the state and extract what we need before dropping the lock
                let mut receiver = {
                    let entry_guard = entry_guard.read().await;
                    trace!("acquired slot read lock");
                    match &*entry_guard {
                        SlotState::Ready(v) => return Ok(v.clone()),
                        SlotState::Pending(ch) => ch.resubscribe(),
                        SlotState::Error(e) => return Err(e.clone()),
                    }
                }; // read lock dropped here

                // Now wait on the channel without holding any locks
                trace!("waiting for database fetch to complete");
                match receiver.recv().await {
                    Ok(result) => return result,
                    Err(_e) => return Err(OpsError::WorkerFailedStrangely.into()),
                }
            }

            // Create a new cache slot and insert and lock it.
            let (complete_tx, complete_rx) = broadcast::channel(1);
            let slot = Arc::new(RwLock::new(SlotState::Pending(complete_rx)));
            cache_guard.push(k.clone(), slot.clone());
            self.len.store(cache_guard.len(), Ordering::Relaxed);

            (slot, complete_tx)
        };

        // Make the fetch.
        let fetch_res = fetch_fn().await;

        // Some error logging before we try to acquire locks.
        if let Err(e) = fetch_res.as_ref() {
            error!(%e, "failed to make database fetch");
        }

        // And then re-acquire the lock on the slot before handling the result.
        let mut slot_guard = slot.write().await;
        trace!("acquired slot write lock");
        match fetch_res {
            Ok(v) => {
                // Store value in slot and broadcast
                *slot_guard = SlotState::Ready(v.clone());
                let _ = complete_tx.send(Ok(v.clone()));
                Ok(v)
            }

            Err(err) => {
                // Store error in slot and broadcast
                *slot_guard = SlotState::Error(err.clone());
                let _ = complete_tx.send(Err(err.clone()));
                drop(slot_guard);
                let mut cache_guard = self.cache.lock().await;
                trace!("re-acquired cache lock");
                safely_remove_cache_slot(&mut cache_guard, k, &slot);
                self.len.store(cache_guard.len(), Ordering::Relaxed);

                Err(err)
            }
        }
    }

    /// Returns a clone of an entry from the cache or invokes some function to load it from
    /// the underlying database.
    pub fn get_or_fetch_blocking(
        &self,
        k: &K,
        fetch_fn: impl Fn() -> Result<V, E>,
    ) -> Result<V, E> {
        // The flow control here is kinda weird, I don't like it.  The key here is that we want to
        // ensure the lock on the whole cache is as short-lived as possible while we check to see if
        // the entry we're looking for is there.  If it's not, then we want to insert a reservation
        // that we hold a lock to and then release the cache-level lock.
        let (slot, complete_tx) = {
            let mut cache_guard = self.cache.blocking_lock();
            if let Some(entry_guard) = cache_guard.get(k).cloned() {
                drop(cache_guard);

                // Get the state and extract what we need before dropping the lock
                let mut receiver = {
                    let entry_guard = entry_guard.blocking_read();
                    trace!("acquired slot read lock");
                    match &*entry_guard {
                        SlotState::Ready(v) => return Ok(v.clone()),
                        SlotState::Pending(ch) => ch.resubscribe(),
                        SlotState::Error(e) => return Err(e.clone()),
                    }
                }; // read lock dropped here

                // Now wait on the channel without holding any locks
                trace!("waiting for database fetch to complete");
                match receiver.blocking_recv() {
                    Ok(result) => return result,
                    Err(_e) => return Err(OpsError::WorkerFailedStrangely.into()),
                }
            }

            // Create a new cache slot and insert and lock it.
            let (complete_tx, complete_rx) = broadcast::channel(1);
            let slot = Arc::new(RwLock::new(SlotState::Pending(complete_rx)));
            cache_guard.push(k.clone(), slot.clone());
            self.len.store(cache_guard.len(), Ordering::Relaxed);

            (slot, complete_tx)
        };

        // Load the entry and insert it into the slot we've already reserved.
        let fetch_res = fetch_fn();

        // Some error logging before we try to acquire locks.
        if let Err(e) = fetch_res.as_ref() {
            warn!(%e, "failed to make database fetch");
        }

        // And then re-acquire the lock on the slot before handling the result.
        let mut slot_guard = slot.blocking_write();
        trace!("re-acquired slot lock");
        match fetch_res {
            Ok(v) => {
                // Store value in slot and broadcast
                *slot_guard = SlotState::Ready(v.clone());
                let _ = complete_tx.send(Ok(v.clone()));
                Ok(v)
            }

            Err(e) => {
                // Store error in slot and broadcast
                *slot_guard = SlotState::Error(e.clone());
                let _ = complete_tx.send(Err(e.clone()));
                drop(slot_guard);
                let mut cache_guard = self.cache.blocking_lock();
                trace!("re-acquired cache lock");
                safely_remove_cache_slot(&mut cache_guard, k, &slot);
                self.len.store(cache_guard.len(), Ordering::Relaxed);

                Err(e)
            }
        }
    }
}

/// Convenience function to safely remove a cache slot key from the cache, iff
/// it matches an expected value. Returns if it did the removal.
///
/// The key may be absent when this runs: the fetch paths release the cache lock
/// while the database read is in flight, so LRU eviction, `purge_*`, or `clear`
/// can drop our pending slot. A missing key means "not removed by us".
fn safely_remove_cache_slot<K: Eq + Hash, V, E>(
    cache: &mut lru::LruCache<K, CacheSlot<V, E>>,
    key: &K,
    slot: &CacheSlot<V, E>,
) -> bool {
    let is_eq = cache
        .peek(key)
        .is_some_and(|existing| Arc::ptr_eq(existing, slot));
    if is_eq {
        cache.pop(key);
    }
    is_eq
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use std::thread;
    use std::time::{Duration, Instant};

    use thiserror::Error;
    use tokio::time::{sleep, timeout};

    use crate::exec::OpsError;

    #[derive(Debug, Clone, Error)]
    enum DbError {
        #[error("resource busy")]
        Busy,
        #[error("entry with idx does not exist")]
        NonExistentEntry,
        #[error("worked task exited strangely")]
        WorkerFailedStrangely,
    }

    impl From<OpsError> for DbError {
        fn from(value: OpsError) -> Self {
            match value {
                OpsError::WorkerFailedStrangely => DbError::WorkerFailedStrangely,
            }
        }
    }

    type CacheTable<K, V> = super::CacheTable<K, V, DbError>;

    #[tokio::test]
    async fn test_basic_async() {
        let cache = CacheTable::<u64, u64>::new(3.try_into().unwrap());

        let res = cache
            .get_or_fetch(&42, || async { Ok(10) })
            .await
            .expect("test: cache gof");
        assert_eq!(res, 10);

        let res = cache
            .get_or_fetch(&42, || async { Err(DbError::Busy) })
            .await
            .expect("test: load gof");
        assert_eq!(res, 10);

        cache.insert_async(42, 12).await;
        let res = cache
            .get_or_fetch(&42, || async { Err(DbError::Busy) })
            .await
            .expect("test: load gof");
        assert_eq!(res, 12);

        let len = cache.get_len_async().await;
        assert_eq!(len, 1);
        cache.purge_async(&42).await;
        let len = cache.get_len_async().await;
        assert_eq!(len, 0);
    }

    #[test]
    fn test_basic_blocking() {
        let cache = CacheTable::<u64, u64>::new(3.try_into().unwrap());

        let res = cache
            .get_or_fetch_blocking(&42, || Ok(10))
            .expect("test: cache gof");
        assert_eq!(res, 10);

        let res = cache
            .get_or_fetch_blocking(&42, || Err(DbError::Busy))
            .expect("test: load gof");
        assert_eq!(res, 10);

        cache.insert_blocking(42, 12);
        let res = cache
            .get_or_fetch_blocking(&42, || Err(DbError::Busy))
            .expect("test: load gof");
        assert_eq!(res, 12);

        let len = cache.get_len_blocking();
        assert_eq!(len, 1);
        cache.purge_blocking(&42);
        let len = cache.get_len_blocking();
        assert_eq!(len, 0);
    }

    #[test]
    fn test_len_tracks_lru_eviction() {
        // Capacity 3: inserting a 4th key should evict the oldest, len stays 3.
        let cache = CacheTable::<u64, u64>::new(3.try_into().unwrap());

        for k in 0..3 {
            cache.insert_blocking(k, k * 10);
        }
        assert_eq!(cache.get_len_blocking(), 3);

        // This evicts key 0.
        cache.insert_blocking(3, 30);
        assert_eq!(cache.get_len_blocking(), 3);

        // Evicted key should miss, new key should hit.
        let res = cache.get_or_fetch_blocking(&0, || Ok(999));
        assert_eq!(res.unwrap(), 999); // fetched, not cached
                                       // Now we have 4 inserts into a cap-3 cache, so still 3.
        assert_eq!(cache.get_len_blocking(), 3);
    }

    #[tokio::test]
    async fn test_deadlock_scenario() {
        let cache = Arc::new(CacheTable::<u64, u64>::new(3.try_into().unwrap()));
        let key = 42u64;

        // Task 1: Creates a pending slot and starts a slow fetch
        let cache1 = cache.clone();
        let task1 = tokio::spawn(async move {
            cache1
                .get_or_fetch(&key, || async {
                    // Simulate a slow database operation.
                    sleep(Duration::from_millis(100)).await;
                    Ok(100)
                })
                .await
        });

        // Small delay to ensure task1 creates the pending slot first
        sleep(Duration::from_millis(10)).await;

        // Task 2: Tries to read from the same key (will find pending slot)
        let cache2 = cache.clone();
        let task2 = tokio::spawn(async move {
            cache2
                .get_or_fetch(&key, || async {
                    // This should never be called since the slot already exists
                    panic!("This fetch function should not be called");
                })
                .await
        });

        // Use timeout to detect deadlock - in deadlock scenario this will timeout
        let timeout_result = timeout(Duration::from_secs(2), async {
            let (result1, result2) = tokio::join!(task1, task2);
            match (result1, result2) {
                (Ok(val1), Ok(val2)) => Ok((val1, val2)),
                (Err(e), _) | (_, Err(e)) => Err(e),
            }
        })
        .await;

        match timeout_result {
            Ok(Ok((Ok(val1), Ok(val2)))) => {
                // No deadlock - both tasks completed successfully
                assert_eq!(val1, 100);
                assert_eq!(val2, 100);
            }
            Ok(Ok((Err(e), _))) | Ok(Ok((_, Err(e)))) => {
                panic!("Database error: {e:?}");
            }
            Ok(Err(e)) => {
                panic!("Task join error: {e:?}");
            }
            Err(_) => {
                // Timeout occurred - indicates deadlock
                panic!("DEADLOCK DETECTED: Tasks timed out after 2 seconds");
            }
        }
    }

    #[test]
    fn test_deadlock_scenario_blocking() {
        let cache = Arc::new(CacheTable::<u64, u64>::new(3.try_into().unwrap()));
        let key = 42u64;

        // Task 1: Creates a pending slot and starts a slow fetch
        let cache1 = cache.clone();
        let handle1 = thread::spawn(move || {
            cache1.get_or_fetch_blocking(&key, || {
                // Simulate slow database operation
                thread::sleep(Duration::from_millis(100));
                Ok(100)
            })
        });

        // Small delay to ensure task1 creates the pending slot first
        thread::sleep(Duration::from_millis(10));

        // Task 2: Tries to read from the same key (will find pending slot)
        let cache2 = cache.clone();
        let handle2 = thread::spawn(move || {
            cache2.get_or_fetch_blocking(&key, || {
                // This should never be called since the slot already exists
                panic!("This fetch function should not be called");
            })
        });

        // Use timeout to detect deadlock - in deadlock scenario this will timeout
        let start_time = Instant::now();
        let timeout_duration = Duration::from_secs(2);

        // Wait for both threads with timeout
        let result1 = wait_for_thread_with_timeout(handle1, timeout_duration);
        let result2 = wait_for_thread_with_timeout(handle2, timeout_duration);

        let elapsed = start_time.elapsed();

        match (result1, result2) {
            (Some(Ok(Ok(val1))), Some(Ok(Ok(val2)))) => {
                // No deadlock - both tasks completed successfully
                assert_eq!(val1, 100);
                assert_eq!(val2, 100);
            }
            (Some(Ok(Err(e))), _) | (_, Some(Ok(Err(e)))) => {
                panic!("Database error: {e:?}");
            }
            (Some(Err(e)), _) | (_, Some(Err(e))) => {
                panic!("Thread panic: {e:?}");
            }
            _ => {
                // Timeout occurred - indicates deadlock
                if elapsed >= timeout_duration {
                    panic!("DEADLOCK DETECTED: Tasks timed out after {elapsed:?}");
                } else {
                    panic!("Thread join failed unexpectedly");
                }
            }
        }
    }

    fn wait_for_thread_with_timeout<T>(
        handle: thread::JoinHandle<T>,
        timeout: Duration,
    ) -> Option<thread::Result<T>> {
        let start = Instant::now();
        loop {
            if handle.is_finished() {
                return Some(handle.join()); // Thread is finished, try to join
            }
            if start.elapsed() >= timeout {
                return None; // Timeout reached
            }
            thread::sleep(Duration::from_millis(1));
        }
    }

    #[tokio::test]
    async fn test_concurrent_error_propagation() {
        let cache = Arc::new(CacheTable::<u64, u64>::new(3.try_into().unwrap()));
        let key = 42u64;

        // Task 1: Creates a pending slot and will return a specific DbError
        let cache1 = cache.clone();
        let task1 = tokio::spawn(async move {
            cache1
                .get_or_fetch(&key, || async {
                    // Simulate a slow database operation that returns a specific error.
                    sleep(Duration::from_millis(50)).await;
                    Err(DbError::NonExistentEntry) // Specific error
                })
                .await
        });

        // Small delay to ensure task1 creates the pending slot first
        sleep(Duration::from_millis(10)).await;

        // Task 2: Tries to read from the same key (will find pending slot)
        let cache2 = cache.clone();
        let task2 = tokio::spawn(async move {
            cache2
                .get_or_fetch(&key, || async {
                    // This should never be called since the slot already exists
                    panic!("This fetch function should not be called");
                })
                .await
        });

        // Wait for both tasks to complete
        let (result1, result2) = tokio::join!(task1, task2);

        let error1 = result1
            .expect("Task 1 should not panic")
            .expect_err("Task 1 should return error");
        let error2 = result2
            .expect("Task 2 should not panic")
            .expect_err("Task 2 should return error");

        // Both tasks should get the same specific DbError::NonExistentEntry
        assert!(
            matches!(error1, DbError::NonExistentEntry),
            "Task 1 should get DbError::NonExistentEntry, got: {error1:?}",
        );
        assert!(
            matches!(error2, DbError::NonExistentEntry),
            "Task 2 should also get DbError::NonExistentEntry, got: {error1:?}",
        );
    }

    #[test]
    fn test_concurrent_error_propagation_blocking() {
        let cache = Arc::new(CacheTable::<u64, u64>::new(3.try_into().unwrap()));
        let key = 42u64;

        // Task 1: Creates a pending slot and will return a specific DbError
        let cache1 = cache.clone();
        let handle1 = thread::spawn(move || {
            cache1.get_or_fetch_blocking(&key, || {
                // Simulate slow database operation that returns specific error
                thread::sleep(Duration::from_millis(50));
                Err(DbError::NonExistentEntry) // Specific error
            })
        });

        // Small delay to ensure task1 creates the pending slot first
        thread::sleep(Duration::from_millis(10));

        // Task 2: Tries to read from the same key (will find pending slot)
        let cache2 = cache.clone();
        let handle2 = thread::spawn(move || {
            cache2.get_or_fetch_blocking(&key, || {
                // This should never be called since the slot already exists
                panic!("This fetch function should not be called");
            })
        });

        // Wait for both threads to complete
        let result1 = handle1.join().expect("Thread 1 should not panic");
        let result2 = handle2.join().expect("Thread 2 should not panic");

        let error1 = result1.expect_err("Task 1 should return error");
        let error2 = result2.expect_err("Task 2 should return error");

        // Both tasks should get the same specific DbError::NonExistentEntry
        assert!(
            matches!(error1, DbError::NonExistentEntry),
            "Task 1 should get DbError::NonExistentEntry, got: {error1:?}"
        );
        assert!(
            matches!(error2, DbError::NonExistentEntry),
            "Task 2 should also get DbError::NonExistentEntry, got: {error1:?}"
        );
    }

    #[test]
    fn test_error_cleanup_after_slot_evicted() {
        // The failing fetch's cleanup must not panic when its pending slot was
        // already removed (here via LRU eviction) during the fetch window.
        let cache = CacheTable::<u64, u64>::new(1.try_into().unwrap());

        let res = cache.get_or_fetch_blocking(&1, || {
            // Evict key 1's pending slot before the fetch returns an error.
            cache.insert_blocking(2, 20);
            Err(DbError::NonExistentEntry)
        });
        assert!(res.is_err());

        // The evicting insert is the sole survivor; cleanup left it untouched.
        assert_eq!(cache.get_len_blocking(), 1);
        let res = cache.get_or_fetch_blocking(&2, || Err(DbError::Busy));
        assert_eq!(res.unwrap(), 20);
    }

    #[test]
    fn test_len_after_error_removal() {
        let cache = CacheTable::<u64, u64>::new(3.try_into().unwrap());

        // Fetch that fails — slot is inserted then removed on error.
        let res = cache.get_or_fetch_blocking(&1, || Err(DbError::NonExistentEntry));
        assert!(res.is_err());
        assert_eq!(cache.get_len_blocking(), 0, "failed slot should be removed");

        // Successful fetch to confirm len goes to 1.
        let res = cache.get_or_fetch_blocking(&2, || Ok(42));
        assert_eq!(res.unwrap(), 42);
        assert_eq!(cache.get_len_blocking(), 1);

        // Another failure doesn't corrupt the count.
        let res = cache.get_or_fetch_blocking(&3, || Err(DbError::Busy));
        assert!(res.is_err());
        assert_eq!(
            cache.get_len_blocking(),
            1,
            "only the successful entry remains"
        );
    }
}
