[package]
name = "strata-ol-state-container"
version = "0.1.0"
edition = "2024"

[dependencies]
ssz.workspace = true
strata-identifiers.workspace = true
strata-ol-state-types.workspace = true
strata-ol-state-types-v1.workspace = true

serde.workspace = true
serde_bytes.workspace = true
thiserror.workspace = true

proptest = { optional = true, workspace = true }

[dev-dependencies]
strata-acct-types.workspace = true
strata-ol-state-types-v1 = { workspace = true, features = ["test-utils"] }

ciborium.workspace = true
proptest.workspace = true

[features]
test-utils = ["dep:proptest", "strata-ol-state-types-v1/test-utils"]

[lints]
workspace = true
