//! Error types for the chain worker.

use strata_db_types::errors::DbError;
use strata_identifiers::{OLBlockCommitment, OLBlockId};
use strata_ledger_types::StateError;
use strata_primitives::epoch::EpochCommitment;
use thiserror::Error;

/// Return type for worker messages.
pub type WorkerResult<T> = Result<T, WorkerError>;

/// Errors that can occur during chain worker operations.
#[derive(Debug, Error)]
pub enum WorkerError {
    /// Block not found in database.
    #[error("missing OL block {0}")]
    MissingOLBlock(OLBlockId),

    /// This usually means that we didn't execute the previous block.
    #[error("missing pre-state to execute block {0:?}")]
    MissingPreState(OLBlockCommitment),

    /// This might point to a database corruption or misused admin commands.
    /// The worker should not have tried to access block outputs that are missing.
    #[error("missing exec output for block {0:?}")]
    MissingBlockOutput(OLBlockCommitment),

    /// Missing write batch for a specific block, used for post-state reconstruction.
    #[error("missing write batch for block {0:?}")]
    MissingWriteBatch(OLBlockCommitment),

    /// This means that we haven't executed the block that's the terminal for an epoch.
    #[error("missing inner post-state of epoch {0} terminal {1:?}")]
    MissingEpochInnerPostState(u64, OLBlockCommitment),

    /// Missing epoch summary for the given commitment.
    #[error("missing summary for epoch commitment {0:?}")]
    MissingEpochSummary(EpochCommitment),

    /// Missing epoch summary for given epoch.
    #[error("missing summary for epoch {0:?}")]
    MissingSummaryForEpoch(u32),

    /// Missing checkpoint payload for an epoch the worker was asked to apply.
    #[error("missing checkpoint payload for epoch {0:?}")]
    MissingCheckpointPayload(EpochCommitment),

    /// Checkpoint sync was asked to apply epoch 0, which is always
    /// genesis-initialized locally and never reconstructed from a checkpoint.
    #[error("cannot apply checkpoint for epoch 0 (genesis-initialized)")]
    CannotApplyGenesisEpoch,

    /// Generated by the worker handle when the worker has exited before being
    /// able to process a message we were trying to send.
    #[error("chain worker exited")]
    WorkerExited,

    /// STF execution error.
    #[error("STF execution failure: {0}")]
    StfExecution(#[from] strata_ol_stf::ExecError),

    /// Write-batch application failed when committing executed-block state.
    #[error("apply_write_batch failed at {commitment:?}: {source}")]
    ApplyWriteBatch {
        commitment: OLBlockCommitment,
        #[source]
        source: StateError,
    },

    /// Database error.
    #[error("database failure: {0}")]
    Database(#[from] DbError),

    /// A log payload was not a well-formed msg-fmt envelope.
    #[error("malformed OL log envelope: {0}")]
    MalformedLogEnvelope(#[from] strata_msg_fmt::Error),

    /// A snark-account update log failed to decode while sourcing index `extra_data`.
    #[error("failed to decode snark-account update log: {0}")]
    SnarkUpdateLogDecode(#[from] strata_ol_chain_types_new::LogDecodeError),

    /// The emitted snark-account update logs could not be paired 1:1 with the tracked snark
    /// state updates when sourcing index `extra_data`.
    #[error("snark update log/index count mismatch (expected {expected}, got {found})")]
    SnarkUpdateLogCountMismatch { expected: usize, found: usize },

    /// A snark-account update log did not line up with its tracked state update.
    #[error("snark update log next_read_idx mismatch (expected {expected}, got {found})")]
    SnarkUpdateLogMismatch { expected: u64, found: u64 },

    /// Missing a required dependency for operation.
    #[error("missing required dependency: {0}")]
    MissingDependency(&'static str),

    /// Worker shutdown before genesis was processed.
    #[error("shutdown before genesis")]
    ShutdownBeforeGenesis,

    /// Genesis block not found at slot 0.
    #[error("genesis block not found at slot 0")]
    MissingGenesisBlock,

    /// Worker has not been initialized yet.
    #[error("worker not initialized")]
    NotInitialized,

    /// Generic unexpected error.
    #[error("unexpected failure: {0}")]
    Unexpected(String),

    /// Functionality not yet implemented.
    #[error("not yet implemented")]
    Unimplemented,
}
