#!/usr/bin/env bash
set -euo pipefail

# Generate cryptographic keys for a single alpen-client sequencer deployment.
#
# Produces:
#   configs/alpen-client/sequencer-schnorr.hex  (Schnorr private key)
#   configs/alpen-client/jwt.hex                (Engine API JWT secret)
#   .env.alpen-client                           (environment file for docker-compose)
#
# Usage:
#   ./init-alpen-client-keys.sh
#   docker compose --env-file .env.alpen-client -f docker-compose-alpen-client.yml up

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/configs/alpen-client"

echo "==> Checking prerequisites..."

# Find a Python interpreter that has coincurve installed.
PYTHON=""
for candidate in python3 python3.12 python3.11 python3.10 python; do
    if command -v "${candidate}" &>/dev/null && "${candidate}" -c "import coincurve" 2>/dev/null; then
        PYTHON="${candidate}"
        break
    fi
done

if [ -z "${PYTHON}" ]; then
    echo "ERROR: No Python interpreter with 'coincurve' found."
    echo "Install it with: pip install coincurve"
    exit 1
fi

echo "    Using Python: $(command -v "${PYTHON}") ($(${PYTHON} --version 2>&1))"

echo "==> Creating output directory: ${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"

# ---------------------------------------------------------------------------
# Helper: generate 32 random bytes as hex
# ---------------------------------------------------------------------------
generate_secret_key() {
    od -An -tx1 -N32 /dev/urandom | tr -d ' \n'
}

# ---------------------------------------------------------------------------
# Helper: derive x-only (Schnorr) public key from a 32-byte hex private key.
# Returns 64 hex chars (32 bytes) — the x-coordinate of the public key.
# ---------------------------------------------------------------------------
derive_schnorr_pubkey() {
    local privkey_hex="$1"
    echo -n "${privkey_hex}" | "${PYTHON}" -c "
import coincurve
import sys

privkey_bytes = bytes.fromhex(sys.stdin.read())
pk = coincurve.PublicKey.from_secret(privkey_bytes)
# Compressed is 33 bytes: prefix || x-coordinate
compressed = pk.format(compressed=True)
# x-only = drop the 1-byte prefix
sys.stdout.write(compressed[1:].hex())
"
}

# ---------------------------------------------------------------------------
# Generate Sequencer Schnorr keypair (for gossip signing)
# ---------------------------------------------------------------------------
echo "==> Generating sequencer Schnorr keypair..."

SCHNORR_KEY="${OUTPUT_DIR}/sequencer-schnorr.hex"

if [ -f "${SCHNORR_KEY}" ]; then
    echo "    ${SCHNORR_KEY} already exists, skipping."
else
    generate_secret_key > "${SCHNORR_KEY}"
    echo "    Created ${SCHNORR_KEY}"
fi

SCHNORR_PRIVKEY=$(cat "${SCHNORR_KEY}")
SCHNORR_PUBKEY=$(derive_schnorr_pubkey "${SCHNORR_PRIVKEY}")

echo "    Sequencer Schnorr pubkey: ${SCHNORR_PUBKEY}"

# ---------------------------------------------------------------------------
# Generate JWT secret (shared between strata OL and alpen-client for
# Engine API authentication)
# ---------------------------------------------------------------------------
echo "==> Generating JWT secret..."

JWT_FILE="${OUTPUT_DIR}/jwt.hex"

if [ -f "${JWT_FILE}" ]; then
    echo "    ${JWT_FILE} already exists, skipping."
else
    generate_secret_key > "${JWT_FILE}"
    echo "    Created ${JWT_FILE}"
fi

# ---------------------------------------------------------------------------
# Write .env.alpen-client
# ---------------------------------------------------------------------------
ENV_FILE="${SCRIPT_DIR}/.env.alpen-client"

echo "==> Writing ${ENV_FILE}..."

cat > "${ENV_FILE}" <<EOF
# Generated by init-alpen-client-keys.sh — do not edit manually.
# Re-run the script to regenerate (existing keys are preserved).

# --- Sequencer Schnorr keys (gossip signing) --------------------------------
SEQUENCER_PRIVATE_KEY=${SCHNORR_PRIVKEY}
SEQUENCER_PUBKEY=${SCHNORR_PUBKEY}

# --- Chain spec (dev | devnet | testnet) ------------------------------------
CHAIN_SPEC=${CHAIN_SPEC:-testnet}

# --- Bitcoin RPC -------------------------------------------------------------
BITCOIND_RPC_USER=${BITCOIND_RPC_USER:-rpcuser}
BITCOIND_RPC_PASSWORD=${BITCOIND_RPC_PASSWORD:-rpcpassword}

# --- Logging ----------------------------------------------------------------
RUST_LOG=${RUST_LOG:-info}
EOF

echo ""
echo "=== Done ==="
echo ""
echo "Generated files:"
echo "  Schnorr key:    ${SCHNORR_KEY}"
echo "  JWT secret:     ${JWT_FILE}"
echo "  Environment:    ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  cd ${SCRIPT_DIR}"
echo "  docker compose --env-file .env.alpen-client -f docker-compose-alpen-client.yml build"
echo "  docker compose --env-file .env.alpen-client -f docker-compose-alpen-client.yml up"
