#![expect(deprecated, reason = "legacy old code is retained for compatibility")] // Don't know how to make clippy happy with precise line expects
//! Macro trait def for the `strata_` RPC namespace using jsonrpsee.
use jsonrpsee::{core::RpcResult, proc_macros::rpc};
use strata_checkpoint_types::EpochSummary;
use strata_csm_types::ClientUpdateOutput;
use strata_ol_bridge_types::PublickeyTable;
use strata_primitives::{epoch::EpochCommitment, l1::L1BlockId, L1Height, L2BlockId};
#[expect(deprecated, reason = "legacy old code is retained for compatibility")]
use strata_rpc_types::{
    types::{RpcBlockHeader, RpcClientStatus, RpcL1Status},
    HexBytes, HexBytes32, L2BlockStatus, RpcCheckpointConfStatus, RpcCheckpointInfo,
    RpcDepositEntry, RpcExecUpdate, RpcSyncStatus, RpcWithdrawalAssignment,
};

#[cfg_attr(not(feature = "client"), rpc(server, namespace = "strata"))]
#[cfg_attr(feature = "client", rpc(server, client, namespace = "strata"))]
#[deprecated(
    note = "use `strata_ol_rpc_api::{OLClientRpc, OLFullNodeRpc}` for OL/EE-decoupled RPC surfaces"
)]
pub trait StrataApi {
    /// Get blocks at a certain height
    #[method(name = "getBlocksAtIdx")]
    async fn get_blocks_at_idx(&self, idx: u64) -> RpcResult<Vec<HexBytes32>>;

    #[method(name = "protocolVersion")]
    async fn protocol_version(&self) -> RpcResult<u64>;

    #[method(name = "blockTime")]
    async fn block_time(&self) -> RpcResult<u64>;

    #[method(name = "l1connected")]
    async fn get_l1_connection_status(&self) -> RpcResult<bool>;

    #[method(name = "l1status")]
    async fn get_l1_status(&self) -> RpcResult<RpcL1Status>;

    #[method(name = "getL1blockHash")]
    async fn get_l1_block_hash(&self, height: L1Height) -> RpcResult<Option<String>>;

    #[method(name = "clientStatus")]
    async fn get_client_status(&self) -> RpcResult<RpcClientStatus>;

    #[method(name = "getRecentBlockHeaders")]
    async fn get_recent_block_headers(&self, count: u64) -> RpcResult<Vec<RpcBlockHeader>>;

    #[method(name = "getHeadersAtIdx")]
    async fn get_headers_at_idx(&self, index: u64) -> RpcResult<Option<Vec<RpcBlockHeader>>>;

    #[method(name = "getHeaderById")]
    async fn get_header_by_id(&self, block_id: L2BlockId) -> RpcResult<Option<RpcBlockHeader>>;

    #[method(name = "getExecUpdateById")]
    async fn get_exec_update_by_id(&self, block_id: L2BlockId) -> RpcResult<Option<RpcExecUpdate>>;

    /// Fetches the list of epoch commitments that have been stored for an
    /// epoch.
    #[method(name = "getEpochCommitments")]
    async fn get_epoch_commitments(&self, epoch: u64) -> RpcResult<Vec<EpochCommitment>>;

    /// Fetches a particular epoch summary.
    #[method(name = "getEpochSummary")]
    async fn get_epoch_summary(
        &self,
        epoch: u64,
        slot: u64,
        terminal: L2BlockId,
    ) -> RpcResult<Option<EpochSummary>>;

    #[method(name = "getChainstateRaw")]
    async fn get_chainstate_raw(&self, block_id: L2BlockId) -> RpcResult<Vec<u8>>;

    #[method(name = "getCLBlockWitness")]
    async fn get_cl_block_witness_raw(&self, block_id: L2BlockId) -> RpcResult<Vec<u8>>;

    #[method(name = "getCurrentDeposits")]
    async fn get_current_deposits(&self) -> RpcResult<Vec<u32>>;

    #[method(name = "getCurrentDepositById")]
    async fn get_current_deposit_by_id(&self, deposit_id: u32) -> RpcResult<RpcDepositEntry>;

    #[method(name = "getCurrentWithdrawalAssignments")]
    async fn get_current_withdrawal_assignments(&self) -> RpcResult<Vec<RpcWithdrawalAssignment>>;

    // block sync methods
    #[method(name = "syncStatus")]
    async fn sync_status(&self) -> RpcResult<RpcSyncStatus>;

    /// Get blocks in range as raw bytes of borsh serialized `Vec<L2BlockBundle>`.
    /// `start_height` and `end_height` are inclusive.
    #[deprecated(note = "use `getRawBlocksRange` in `strata_ol_rpc_api::OLFullNodeRpc`")]
    #[method(name = "getRawBundles")]
    async fn get_raw_bundles(&self, start_height: u64, end_height: u64) -> RpcResult<HexBytes>;

    #[deprecated(note = "use `getRawBlockById` in `strata_ol_rpc_api::OLFullNodeRpc`")]
    #[method(name = "getRawBundleById")]
    async fn get_raw_bundle_by_id(&self, block_id: L2BlockId) -> RpcResult<Option<HexBytes>>;

    /// Get message by scope, Currently either Deposit or Withdrawal
    #[method(name = "getBridgeMsgsByScope")]
    async fn get_msgs_by_scope(&self, scope: HexBytes) -> RpcResult<Vec<HexBytes>>;

    /// Submit raw messages
    #[method(name = "submitBridgeMsg")]
    async fn submit_bridge_msg(&self, raw_msg: HexBytes) -> RpcResult<()>;

    /// Get the operators' public key table that is used to sign transactions and messages.
    ///
    /// # Note
    ///
    /// The rollup chain state only has the `XOnlyPublicKey`.
    /// The `PublicKey` in the [`PublickeyTable`] is generated by
    /// assuming an even parity as per the final schema in [`BIP 340`](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki#design)
    // TODO(STR-2170): consider adding a separate method to get the message signing key which may
    // not be the same as the wallet key if we decide to change the signature scheme.
    #[method(name = "getActiveOperatorChainPubkeySet")]
    async fn get_active_operator_chain_pubkey_set(&self) -> RpcResult<PublickeyTable>;

    /// Get latest checkpoint info
    #[deprecated(note = "use OL checkpoint/chain status RPCs in `strata_ol_rpc_api`")]
    #[method(name = "getLatestCheckpointIndex")]
    async fn get_latest_checkpoint_index(&self, finalized: Option<bool>) -> RpcResult<Option<u64>>;

    /// Get latest checkpoint index that still needs proof generation
    #[deprecated(note = "use OL checkpoint signing/status RPCs in `strata_ol_rpc_api`")]
    #[method(name = "getNextUnprovenCheckpointIndex")]
    async fn get_next_unproven_checkpoint_index(&self) -> RpcResult<Option<u64>>;

    /// Get nth checkpoint info if any
    #[deprecated(note = "use OL checkpoint/account summary RPCs in `strata_ol_rpc_api`")]
    #[expect(deprecated, reason = "legacy old code is retained for compatibility")]
    #[method(name = "getCheckpointInfo")]
    async fn get_checkpoint_info(&self, idx: u64) -> RpcResult<Option<RpcCheckpointInfo>>;

    /// Get the checkpoint confirmation status if checkpoint exists
    #[deprecated(note = "use OL checkpoint signing/status RPCs in `strata_ol_rpc_api`")]
    #[expect(deprecated, reason = "legacy old code is retained for compatibility")]
    #[method(name = "getCheckpointConfStatus")]
    async fn get_checkpoint_conf_status(
        &self,
        idx: u64,
    ) -> RpcResult<Option<RpcCheckpointConfStatus>>;

    /// Get the l2block status from its height
    /// This assumes that the block finalization is always sequential. i.e all the blocks before the
    /// last finalized block are also finalized
    #[deprecated(note = "use `getChainStatus` in `strata_ol_rpc_api::OLClientRpc`")]
    #[expect(deprecated, reason = "legacy old code is retained for compatibility")]
    #[method(name = "getL2BlockStatus")]
    async fn get_l2_block_status(&self, block_height: u64) -> RpcResult<L2BlockStatus>;

    /// Gets the client update output produced as a result of the l1 block processed.
    #[method(name = "getClientUpdateOutput")]
    async fn get_client_update_output(
        &self,
        block: L1BlockId,
    ) -> RpcResult<Option<ClientUpdateOutput>>;
}
