bitcoind_url = "http://127.0.0.1:18443"
bitcoind_rpc_user = "rpc_user"
bitcoind_rpc_password = "rpc_password"
sequencer_pubkey = "1b84c5567b126440995d3ed5aaba0565d71e1834604819ff9c17f5e9d5dd078f"
ee_params = "/path/to/ee-params.json"
