[package]
name = "strata-ol-gchain-impl"
version = "0.3.0-alpha.1"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-asm-checkpoint-types.workspace = true
strata-asm-common.workspace = true
strata-checkpoint-types.workspace = true
strata-gchain-types.workspace = true
strata-identifiers.workspace = true
strata-msg-fmt.workspace = true
strata-ol-chain-types-v1.workspace = true
strata-ol-da-types-v1.workspace = true
strata-ol-params.workspace = true
strata-ol-state-support-types.workspace = true
strata-ol-state-types.workspace = true
strata-ol-state-types-v1.workspace = true
strata-ol-stf-v1.workspace = true
strata-serde-utils.workspace = true
strata-snark-acct-types.workspace = true

ciborium.workspace = true
serde.workspace = true
strata-codec.workspace = true
thiserror.workspace = true

[dev-dependencies]
strata-gchain-executor.workspace = true
strata-ol-params = { workspace = true, features = ["test-defaults"] }
strata-ol-stf-v1 = { workspace = true, features = ["test-utils"] }

[lints]
workspace = true
